### ISSUE TITLE
OPass 後台需求

### ISSUE THREAD

**Issue by kkdai** [golangtw/gophercon2020#14]
Spec 這兩份:
https://hackmd.io/@OPass/S1G_QEnHS
https://hackmd.io/@OPass/rJitRr3VS

開個新 repo ～～用 gin 還是什麼都好
接上 Heroku

**Comment by kkdai** [comment]
https://docs.google.com/document/d/1xyaON8kZ_srdO04_dBuZQ-oY0R9Hkelyz3er0axYXC8/edit

根據會議記錄，
由於只有單軌，不太需要太多大會公告。
決定使用 KKTIX 就好

**Comment by appleboy** [comment]
@kkdai 讚 👍
