### ISSUE TITLE
Review CFP 

### ISSUE THREAD

**Issue by kkdai** [golangtw/gophercon2020#20]
https://www.papercall.io/gophercon-2020-taiwan

**Comment by appleboy** [comment]
@kkdai 沒權限可以修改

before:

> 該演講與 Golan g社區有關

after:

該演講與 `Golang` 社區有關

**Comment by kkdai** [comment]
@syxuan

**Comment by appleboy** [comment]
@kkdai 有這一頁的文案嗎？ https://gophercon.golang.tw/2020/cfp

**Comment by chechiachang** [comment]
我直接把 link 改到外部？
https://www.papercall.io/gophercon-2020-taiwan

**Comment by kkdai** [comment]
直接連 Papercall  好了，剛剛那頁整個像是早到新世界。 “大鳴大放”是哪招？
