### ISSUE TITLE
CFP deadline 

### ISSUE THREAD

**Issue by kkdai** [golangtw/gophercon2020#22]
2020.04.01 開始議程徵稿 Open for CFP
2020.04.30 徵稿截止 Close of CFP
2020.05.29 各別通知 send acceptance and rejection emails
2020.??.?? 公布議程 post schedule
2020.??.?? 錄影 recorded talks will be available through Youtube channel

**Comment by freddy50806** [comment]
因為疫情影響所以CFP徵稿時間順延

**Comment by chenyunchen** [comment]
已截止徵稿，故關閉
