### ISSUE TITLE
Navbar /team 的連結有些使用者會爆掉

### ISSUE THREAD

**Issue by chechiachang** [golangtw/gophercon2020#27]
Navbar link 到 /2020/team
https://gophercon.golang.tw/2020/team/ -> 404
本地測試會自動轉址
http://localhost:8080/2020/team/ -> redirect http://localhost:8080/2020/team/staff

然後 route 有寫 redirect 

https://github.com/golangtw/gophercon2020/blob/de44dad8b2bddcaf076c16d6ef6f5fcbf3779d2a/src/router.ts#L89
但在 github page 上好像不是每個人的網頁都順利 redirect

**Comment by chenyunchen** [comment]
Team這頁比較特殊 底下分成 `sponsor.html` `staff.html`

爆掉原因是 `Server Side Render` 沒有對應的 `index.html`
https://gophercon.golang.tw/2020/team/  -> 對應到的目錄沒有該index.html

大部分的人因為瀏覽器先載完router.js才去點所以順利 redirect
但如果還沒載完的情況下去點就會爆掉

#28

**Comment by chechiachang** [comment]
喔喔
所以 route 裡面寫 redirect 要在 route.js 後生效 @@
先給 /2020/team 一個 default staff 頁面這樣

**Comment by chenyunchen** [comment]
對 我也回報給sitcon 一樣問題

**Comment by chenyunchen** [comment]
先照SITCON那邊有人提的
直接改route就好
