### ISSUE TITLE
新增 中佑集團 至贊助頁面

### ISSUE THREAD

**Issue by david7482** [golangtw/gophercon2020#32]
### 公司 logo
[中佑Logo_橫式_Outline.zip](https://github.com/golangtw/gophercon2020/files/4427955/Logo_._Outline.zip)

### 公司介紹（中文）
中佑集團成立於1999年，為國內具代表地位的遊戲軟體系統開發商， 致力於開發線上遊戲軟體並提供系統整合平台服務，數十年來穩健的經營成功將產品行銷至亞洲各地，除了開發自有品牌旗下更同時擁有關係企業凡谷興業。專業的遊戲研發及設計團隊為後盾，追求最佳品質不間斷的研發創新技術 ，逐步建構亞洲最大網路娛樂事業體。

中佑集團一直是市場上最值得信賴的遊戲軟體系統開發商，我們的目標是亞洲第一的遊戲市佔率，同時與我們的商業夥伴們將多元網路娛樂的業務推廣至全世界，創造雙贏的局面。

### 公司介紹（英文）
The Leading iGaming Software Supplier in Asia.
Founded in 1999, Chung Yo Group has dedicated itself to the development and innovation of new technologies and systems for more than twenty years. Providing professional platform integration services, Chung Yo Group has always been engaged in various international projects to provide a wider and more diversified viewpoint to the industry.

**Comment by chenyunchen** [comment]
update #33
