### ISSUE TITLE
議程頁面資訊

### ISSUE THREAD

**Issue by wiasliaw77210** [golangtw/gophercon2020#72]
Hello, there is an issue for asking api key for `google-spreadsheet-api` due to the package to generate session data in JSON format.

This api key should be under the organization of golangTW(if exist).
After that, please update in `src/util/session/config.js`.

Thanks.

LINK
* [spreadsheet-to-json](https://github.com/revolunet/spreadsheet-to-json#readme)

**Comment by kkdai** [comment]
@YuShuanHsieh Would you please help to check this?

**Comment by chenyunchen** [comment]
Update. If the session spreadsheet is public, we only need spreadsheet key.
Goolge cloud platform credentials is unnecessary.

**Please follow:**
[Session spreadsheet](https://docs.google.com/spreadsheets/d/1xqOmMPLvtUp_8C31ZanwLhK4dhBcmMZyrKLtdh9vVEw)
Fork → PUBLISH → Change spreadsheetKey to `src/util/session/config.js`

**Comment by chenyunchen** [comment]
Update SpreadSheetKey:
e59824f2156a3c6d7a761c9abf6c4b1de529b7a4
