### ISSUE TITLE
團隊成員的頭像更新

### ISSUE THREAD

**Issue by chechiachang** [golangtw/gophercon2020#8]
https://gophercon.golang.tw/2020/team/staff
尚未上傳頭像的夥伴都會是老外

1. 註冊 https://gravatar.com/ 並上傳頭像

2. 發 PR 更新 staff.json
https://github.com/golangtw/gophercon2020/blob/master/public/json/staff.json
emailhash 是註冊用的 email 使用 md5 hash

**Comment by kkdai** [comment]
還沒上傳的記得改喔  my part: a1d2e198d687fd67b4d2bddf27564241378b6110

**Comment by david7482** [comment]
#12 PR~~~

**Comment by iamken1204** [comment]
#17 PR please

**Comment by appleboy** [comment]
@iamken1204 merged.

**Comment by kkdai** [comment]
@easonlin404  你的頭像還有問題  
![image](https://user-images.githubusercontent.com/2252691/76374641-c88e0080-637e-11ea-846d-f882419636fb.png)

**Comment by kkdai** [comment]
Add yourself in working staff

@paristsai @syxuan

**Comment by kkdai** [comment]
add your photo @YuShuanHsieh

**Comment by paristsai** [comment]
#25 PR pls~

**Comment by easonlin404** [comment]
> @easonlin404 你的頭像還有問題
> ![image](https://user-images.githubusercontent.com/2252691/76374641-c88e0080-637e-11ea-846d-f882419636fb.png)

Fixed, thanks for reminding me.

**Comment by appleboy** [comment]
剩下 @kkc 沒有更新。

**Comment by kkc** [comment]
已發 PR !

**Comment by appleboy** [comment]
All Done.

**Comment by appleboy** [comment]
還有一位 HC Tsai

**Comment by appleboy** [comment]
全部完成了。

**Comment by ToastCheng** [comment]
#83 pr please

**Comment by chenyunchen** [comment]
@ToastCheng merge
